name: Test PR
"on": pull_request

jobs:
  install-and-test:
    name: ğŸ› ï¸ Install & Test
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ—œï¸ Checkout
        uses: actions/checkout@v6

      - name: ğŸ—œï¸ Setup node version
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: ğŸ—œï¸ Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: ğŸ› ï¸ Install
        uses: ./.github/actions/cached-deps

      - name: ğŸ› ï¸ Clean temporary files
        run: yarn clean

      - name: ğŸ“¦ Build
        run: yarn build

      - name: ğŸ› ï¸ Setup package
        run: yarn script:package-npm

      - name: ğŸ› ï¸ Copy files to dist
        run: yarn copy-files
